service: api-project
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${env:STAGE, 'dev'}
  region: ${env:REGION, 'us-east-2'}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "sqs:SendMessage"
        - "sqs:ReceiveMessage"
        - "sqs:DeleteMessage"
        - "sqs:GetQueueUrl"
      Resource:
        Fn::GetAtt:
          - FeedQueue
          - Arn

package:
  include:
    - src/**
    - .env

functions:
  getCompanies:
    handler: lambdas/getCompanies.getCompanies
    events:
      - http:
          path: companies
          method: get
  getCompanyById:
    handler: lambdas/getCompanyById.getCompanyById
    events:
      - http:
          path: companies/{company_id}
          method: get
  createJob:
    handler: lambdas/createJob.createJob
    events:
      - http:
          path: job
          method: post
          cors: true

  publishJob:
    handler: lambdas/publishJob.publishJob
    events:
      - http:
          path: job/{job_id}/publish
          method: put
          cors: true

  editJob:
    handler: lambdas/editJob.editJob
    events:
      - http:
          path: job/{job_id}
          method: put
          cors: true

  archiveJob:
    handler: lambdas/archiveJob.archiveJob
    events:
      - http:
          path: job/{job_id}/archive
          method: put
          cors: true

  deleteJob:
    handler: lambdas/deleteJob.deleteJob
    events:
      - http:
          path: job/{job_id}
          method: delete
          cors: true
  getFeed:
    handler: lambdas/getFeed.getFeed
    events:
      - http:
          path: feed
          method: get
          cors: true
      - sqs:
          arn:
            Fn::GetAtt:
              - FeedQueue
              - Arn

  updateFeed:
    handler: lambdas/updateFeed.updateFeed
    events:
      - http:
          path: update-feed
          method: post
          cors: true
resources:
  Resources:
    FeedQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: ${env:QUEUE_NAME, 'feed-queue'}
    MyS3Bucket:
      Type: "AWS::S3::Bucket"
      Properties:
        BucketName: ${env:BUCKET_NAME, 'plooralbucket'}
